language: php

php:
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover